import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { resolve } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Arbourist — source lives in src/
*/
`;

const mode = process.argv[2] ?? "dev";
const nodeIoAlias = { "arbourist-node-io": resolve("src/node-io.cjs") };

const obsidianExternals = [
  "obsidian",
  "electron",
  "@electron/remote",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
];

if (mode === "test") {
  await esbuild.build({
    entryPoints: ["tests/run.ts"],
    bundle: true,
    platform: "node",
    format: "cjs",
    outfile: "tests/run.cjs",
    sourcemap: false,
    logLevel: "info",
    alias: nodeIoAlias,
  });
  await esbuild.build({
    entryPoints: ["tests/ui-run.ts"],
    bundle: true,
    platform: "node",
    format: "cjs",
    outfile: "tests/ui-run.cjs",
    sourcemap: false,
    logLevel: "info",
    external: ["linkedom"],
  });
  process.exit(0);
}

const prod = mode === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: obsidianExternals,
  format: "cjs",
  platform: "node",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  alias: nodeIoAlias,
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
